service: my-app
provider:
  name: azure
  region: West US 2
  runtime: nodejs10.x
  environment:
    VARIABLE_FOO: foo
plugins:
  - serverless-azure-functions
package:
  exclude:
    - local.settings.json
    - .vscode/**
functions:
  timer:
    handler: dist/timer.handler
    events:
      - timer: null
        x-azure-settings:
          schedule: '*/10 * * * * *'
    name: my-app-timer
